### PR TITLE
Replacing "then" method check with instanceof Promise in async 'fs' test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by omrilotan** [comment]
Thanks, Attrash. Makes total sense

**Comment by ghost** [comment]
Thank you so much! Noticed also that you've used Object.assign instead of Object spread syntax, Is there any reason for doing so? (Comparability for older Node versions?)

**Comment by omrilotan** [comment]
Yeah, great observation, @Attrash-Islam .
I feel spreading an object has a high cost (breaking up all of these object and "assigning" them onto a different one, mostly a feeling).
I'm not sure how much more it is syntactically appealing. I wouldn't mind using a spread operator, but don't know if it's superior to `Object.assign`.

image

**Comment by ghost** [comment]
Regards the same syntax that you checked which is `const c = {...a, ...b}` if you transpile that in babel REPL you can see that it will be transpiled exactly like the object-assign syntax!

```js
"use strict";

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

var c = _extends({}, a, b);
```

This particular website of JavaScript profiling not that good and I noticed that it's not stable to be depending on.

If this metrics is correct then we can say that the native Chrome implementation of the object spread don't relay on Object.assign! which sound strange! and will likely be improved in the future since object spread is one of the hottest syntax in the ES6+

Thanks for your precious time

**Pull request merged**
